namespace QuranSchool.Models;

public class StudentPassword
{
    public Student Student { get; set; }
    public Account Account { get; set; }

    public string? Password => Account.AutoGeneratedPassword;
    public bool Changed => !Account.RequiredToChangePassword;

    public string UserName => Account.UserName;
    public string Content => Changed ? "Password Changed by User" : Password;
}